title: Roshan's Blog
email: roshan.venugopal@gmail.com
description: >-
  A casual space for my thoughts, code, and ideas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: roshanvenugopal
github_username: roshanis
linkedin_username: roshanvenugopal

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
